%% Automatically generated, do not edit
%% Generated by gpb_compile version 3.21.0 on {{2018,2,1},{20,10,14}}

-ifndef(rtmp_sample_type).
-define(rtmp_sample_type, true).

-define(rtmp_sample_type_gpb_version, "3.21.0").

-ifndef('RTMP.SAMPLE.TYPE.TYPE_PB_H').
-define('RTMP.SAMPLE.TYPE.TYPE_PB_H', true).
-record('rtmp.sample.type.Type',
        {
        }).
-endif.

-endif.
